language: ruby
rvm:
- 2.2.6
- 2.3.3
- 2.4.0
script: bundle exec rake travis
notifications:
  slack:
    secure: QHLhs1TlJg2gdMzPvaUNXns7ENldARurnJ/wX/ylnAtushcT/0ZKdg+c+tRc8loYYi0lU5xHOtg4WqTh9pa6YRg0+x5xTovKgKUxWkiT0rVYq7cL5buFv9ipkP8DcNzNRvsH7M/QXWbuTqdvLVmyqPCwnJHwfT9Q7fDtpBoDSfnhhm7T8OnOSn68jeckbiAYl1WI2ohV+tQa+CHcSbMbgvlMo91KV5RSy3i3CMcSoWrIl/u5IhQhWqHwDJwur3Cs+H3VBNdCMiIAnYIH/0BDBevuiPt0EhZSISAJL0dx1P75zIp4XyBJAO8U7gkh+MeuqZpwoXZ3rZHfa6TuN2JACiMVf6TImpS3gGC1mhYsHy2pCi2Z0tP3QJP0FWtJBwcvUqxSYbDhWP4nKFSop+LgnC/yWwNVtX2Q3d+q9R2oivWJA2Yjgt6+f+4PwOg/OLR9d3Bc/1fXksXdUinqvONNG4ucIpzS5tWPuMWZhub5w1I8itvNnVDj+owSB72T972tNRnlyLQID/12ZDPY7i2RXK+E+37TcWSPOXkEcve5FI4RWBEbGe8s8w7DZSo9Hhuhj6fRA/e+p3rNj/kmnPjhiCQDFb0cTSUn4goySydy80X4gbY4FIU1jeC0kPd8ioR1Bqrm3uSF0hapN8mQ7uSzOcfbYoxrTXuzW+tyX9Ss+j0=
